version: "3.7"
services:
  web:
    build: ./web
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/audiophile
      NEXT_DEV: 1
    ports:
      - "3000:3000"
    volumes:
      - ./web/src:/app/src
    command: npm run dev
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "audiophile"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  graphql:
    container_name: audiophile-graphql
    restart: always
    image: audiophile-graphql
    build:
        context: ./web/src/graphql
    env_file:
        - ./.env
    depends_on:
        - db
    ports:
        - 5433:5433
    command: ["--connection", "postgres://postgres:postgres@db:5432/audiophile", "--port", "5433", "--schema", "public"]

