export const actions = {
	SHOW_CART: "SHOW_CART",
	ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
	INCREASE_ITEM_QUANTITY: "INCREASE_ITEM_AMOUNT",
	DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_AMOUNT",
	REMOVE_ALL_CART_PRODUCTS: "REMOVE_ALL_CART_PRODUCTS"
};
